### PR TITLE
Fix the parsing of wildcards dependency constraints

### PR DESCRIPTION
**Pull request by sdispater**
Resolves: python-poetry/poetry#4176

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Review by abn — APPROVED** [review]

**Comment by bentheiii** [comment]
I think this fix is incorrect, as `name < 3.*` should accept version`3.6.0`, I think `name < 3.*` should be normalized to `name < 4`

**Comment by finswimmer** [comment]
Hello @bentheiii,

`name < 3.*` could be read as "any version smaller 3.anything". So it's `< 3`.

> I think this fix is incorrect.

Please don't call it a "fix" (even it's in the title ;) ). It's a (temporary) workaround, to mimic pip's wrong behavior of allowing this kind of invalid PEP 440 constraint. Otherwise to many packages cannot be installed anymore. (See also: https://discuss.python.org/t/pep-440-wildcard-usage-in-comparison-clause/10045)

**Comment by bentheiii** [comment]
It is indeed a pretty unclear whether `name (?) X.*` should resolve to "version chosen must match the constraint for **any** `X.*`" or "version chosen must match the constraint for **all** `X.*`". But since `name > 3.*` resolves to `name > 3`, poetry obviously goes with the former. Therefore, `name < 3.*` has to be less than any version `3.*` , it has to only be less than an arbitrarily high `*`, normalizing to `name < 4` (just like how `name > 3.*` must be higher than an arbitrarily low `*`, normalizing to `name > 3`).

**Comment by edgarrmondragon** [comment]
@furlongm is there a reason not to install from `master` in the meantime if the feature you need is there?

**Comment by furlongm** [comment]
> @furlongm is there a reason not to install from `master` in the meantime if the feature you need is there?

Mostly a desire to pin the poetry dependencies at a specific version so it's not a moving target - also don't always have access to github but do have a pypi mirror, so released versions are a lot more accessible.

**Pull request merged**
