### PR TITLE
semver: fix PEP 440 compatible release parsing

### PR DESCRIPTION
**Pull request by abn**
Relates-to: python-poetry/poetry#2734

### CODE REVIEW

**Comment by sdispater** [comment]
It should fix https://github.com/python-poetry/poetry/issues/2737 as well.

**Comment by abn** [comment]
> It fixes the root cause, but not the fact that it failed silently.

@ewjoachim yes that is correct. Unfortunately, we need a better way to handle those logs. The issue is that the failure was handled as expected in the sense that current logic explicitly handles the issue by skipping the dependency. Not ideal. Either we need to raise an error gracefully, or simply propagate the relevant log correctly.

**Comment by PetterS** [comment]
> It fixes the root cause, but not the fact that it failed silently.

Completely agree that we need to aim for much more robustness.

**Comment by ewjoachim** [comment]
@PetterS the "failing silently" part was addressed in #2738 & #2739 by @abn and @sdispater ;)

**Pull request merged**
