### PR TITLE
lint and fix pep8 naming conventions

### PR DESCRIPTION
**Pull request by danieleades**
i'll see what the CI does, but i'm expecting there's a reasonable chance this is a breaking change for downstream

### CODE REVIEW

**Comment by neersighted** [comment]
This will probably cause some breakage, yeah. It's a bigger codebase, but I think this would be good to try in poetry itself first since it has no consumers outside of plugins (and the plugin API is not yet stable).

See python-poetry/poetry#4776.

**Comment by danieleades** [comment]
> This will probably cause some breakage, yeah. It's a bigger codebase, but I think this would be good to try in poetry itself first since it has no consumers outside of plugins (and the plugin API is not yet stable).
> 
> See [python-poetry/poetry#4776](https://github.com/python-poetry/poetry/issues/4776).

downstream tests passed. wasn't expecting that

**Comment by danieleades** [comment]
grepping the code, it's clear that the Exception class is used downstream. I guess the 'downstream' test case doesn't cover it.

I guess both repos will need to be changed together, and it's a major version bump for `core`

**Comment by danieleades** [comment]
rebased

**Comment by finswimmer** [comment]
We could ignore the `N818` error for now, to introduce `pep-naming` anyway.

**Comment by Secrus** [comment]
Superseded by #767, this PR was too much of a rebase hell.

**Pull request closed without merging**
