### PR TITLE
Allow : in Author name.

### PR DESCRIPTION
**Pull request by Amourspirit**
Suport for names such as :Barry-Thomas-Paul: Moss
See: [FOR THE CLAIM OF THE LIFE.](https://www.fortheclaimofthelife.com/)

Resolves: python-poetry#

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by neersighted** [comment]
I'm really unclear on the purpose or value of this (and the linked site seems to be a combo of a sovereign citizen/world citizen/law of attraction sort of thing) -- but setuptools allows it, so I suppose we might as well.

It looks like we don't have any test coverage here -- could you please write a test with good and bad names?

**Review by neersighted — CHANGES_REQUESTED** [review]
Requires tests.

**Comment by Amourspirit** [comment]
> I'm really unclear on the purpose or value of this (and the linked site seems to be a combo of a sovereign citizen/world citizen/law of attraction sort of thing) -- but setuptools allows it, so I suppose we might as well.
> 
> It looks like we don't have any test coverage here -- could you please write a test with good and bad names?

Short version Poetry is blocking my Lawful name.

**Comment by Amourspirit** [comment]
> Requires tests.

All current test are passing. I will add specific test and update PR.

**Review by neersighted — APPROVED** [review]

**Pull request merged**
