### PR TITLE
Build wheel from from dynamically created package via custom build.py

### PR DESCRIPTION
**Pull request by rragundez**
Resolves: python-poetry#8312
https://github.com/python-poetry/poetry/issues/8312

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by rragundez** [comment]
Hi @radoering thanks for fixing the error in the CI. 

Anything else missing or that I need to add to move this PR forward?

**Comment by radoering** [comment]
No, LGTM. It just has to wait for python-poetry/poetry#8369.

**Comment by rragundez** [comment]
@radoering do you know when will the changes are expected to be release in a new version? I need this functionality to submit a PR in Keras Core.

**Comment by radoering** [comment]
We'll probably do a release to officially support Python 3.12. The Python 3.12 release is scheduled for 2023-10-02, so I suppose we'll try to do a release near that date.

**Pull request merged**
