### PR TITLE
Add `authors` to required fields

### PR DESCRIPTION
**Pull request by abitrolly**
Relates-to: https://github.com/python-poetry/poetry/issues/407
Relates-to: https://github.com/python-poetry/poetry/issues/3155

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

    The documentation was fixed in python-poetry/poetry#412

UPDATE: I see this is a duplicate of https://github.com/python-poetry/poetry-core/pull/37 Let me add tests to it.

### CODE REVIEW

**Comment by abitrolly** [comment]
Unable to run tests, because `poetry install` fails. Looking into this.
```
$ poetry install
The lock file might not be compatible with the current version of Poetry.
Upgrade Poetry to ensure the lock file is read properly or, alternatively, regenerate the lock file with the `poetry lock` command.
Installing dependencies from lock file

[RecursionError]
maximum recursion depth exceeded while calling a Python object
```

**Comment by abitrolly** [comment]
@python-poetry/triage this is ready for review.

**Comment by abitrolly** [comment]
This is `hacktoberfest` related PR. Any chance to get it merged before the deadline? Pretty please. :D

**Comment by luni3359** [comment]
While this is now in the documentation, `poetry check` still incorrectly marks the `pyproject.toml`as correct even if the authors key is missing.

**Comment by abitrolly** [comment]
An indentation fix in 44167a577b6cccafb1baef2e42a2991e11d8ea1e made this PR unmergeable. I am looking for a way to fix this.

**Comment by abitrolly** [comment]
Rebased and ready for review again.

**Comment by Secrus** [comment]
Superseeded by #437

**Comment by abitrolly** [comment]
Stealing PRs is unfair! :D

**Pull request closed without merging**
