### PR TITLE
Release 1.0.0rc1

### PR DESCRIPTION
**Pull request by sdispater**
### Fixed

- Fixed Python constraint propagation when converting a package to a dependency ([#84](https://github.com/python-poetry/core/pull/84)).
- Fixed VCS ignored files being included in wheel distributions for projects using the `src` layout ([#81](https://github.com/python-poetry/core/pull/81))

### CODE REVIEW

**Comment by abn** [comment]
Missing: https://github.com/python-poetry/poetry-core/pull/81

**Comment by sdispater** [comment]
@abn Fixed

**Comment by abn** [comment]
@sdispater can you also add this change here? https://github.com/python-poetry/poetry/pull/2962/files seems something is broken on windows.

**Comment by sdispater** [comment]
@abn Done

**Review by abn — APPROVED** [review]

**Pull request merged**
