### PR TITLE
changed code to use default branch if none is specified.

### PR DESCRIPTION
**Pull request by Armaxxx**
Resolves: https://github.com/python-poetry/poetry/issues/3366

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by sinoroc** [comment]
Fixes: https://github.com/python-poetry/poetry/issues/3366 ?

**Comment by Armaxxx** [comment]
So, the tests are failing because they expect "master" to be the default branch, however by removing the branch from the url the default "main" branch will be pulled, however it is named.

**Comment by finswimmer** [comment]
Hello @Armaxxx,

I just took a quick look at this. I think at least this method https://github.com/python-poetry/poetry-core/blob/abe9fe59fd7a0b181463461273c16af8a258a969/poetry/core/packages/vcs_dependency.py#L97 must be adopted, to not add a branch if there is no one defined.

fin swimmer

**Comment by Armaxxx** [comment]
You're right, I completely missed it, adapted.

**Comment by stephsamson** [comment]
Closing in favor of #143. Thank you @Armaxxx.

**Pull request closed without merging**
