### PR TITLE
Release 1.1.0b1

### PR DESCRIPTION
**Pull request by abn**
### Fixed

- Fixed an issue where canonicalize package names leads to infinite loops ([#328](https://github.com/python-poetry/poetry-core/pull/328)).
- Fixed an issue where versions wasn't correct normalized to PEP-440 ([#344](https://github.com/python-poetry/poetry-core/pull/344)).
- Fixed an issue with union of multi markers if one marker is a subset of the other marker ([#352](https://github.com/python-poetry/poetry-core/pull/352)).
- Fixed an issue with markers which are not in disjunctive normal form (DNF) ([#347](https://github.com/python-poetry/poetry-core/pull/347)).
- Fixed an issue where stub-only partial namespace packages were not recognized as packages ([#221](https://github.com/python-poetry/poetry-core/pull/221)).
- Fixed an issue where PEP-508 url requirements with extras were not parsed correctly ([#345](https://github.com/python-poetry/poetry-core/pull/345)).
- Fixed an issue where PEP-508 strings with wildcard exclusion constraints were incorrectly exported ([#343](https://github.com/python-poetry/poetry-core/pull/343)).
- Allow hidden directories on Windows bare repos ([#341](https://github.com/python-poetry/poetry-core/pull/341)).
- Fixed an issue where dependencies with an epoch are parsed as empty ([#316](https://github.com/python-poetry/poetry-core/pull/316)).
- Fixed an issue where a package consisting of multiple packages wasn't build correctly ([#292](https://github.com/python-poetry/poetry-core/pull/292)).

### Added

- Added support for handling git urls with subdirectory ([#288](https://github.com/python-poetry/poetry-core/pull/288)).
- Added support for metadata files as described in PEP-658 for PEP-503 "simple" API repositories ([#333](https://github.com/python-poetry/poetry-core/pull/333)).

### Changed

- Renamed dependency group of runtime dependencies to from `default` to `main` ([#326](https://github.com/python-poetry/poetry-core/pull/326)).

### Improvements

- `poetry-core` is now completely type checked. Special thanks to @dimbleby @branchvincent :tada:
- Improved the SemVer constraint parsing ([#327](https://github.com/python-poetry/poetry-core/pull/327)).
- Improved the speed when cloning git repositories ([#290](https://github.com/python-poetry/poetry-core/pull/290)).

## Pending Pull Requests

- #347
- #344 
- #288 
- #325

### CODE REVIEW

**Comment by abn** [comment]
https://github.com/python-poetry/poetry/pull/5654 should fix the downstream tests.

**Review by radoering — CHANGES_REQUESTED** [review]
As discussed in chat, #325 should be included in order to reveal unintended side effects which require a downstream fix as early as possible before poetry 1.2 release.

**Comment by neersighted** [comment]
> As discussed in chat, #325 should be included in order to reveal unintended side effects which require a downstream fix as early as possible before poetry 1.2 release.

This is merged now.

**Comment by abn** [comment]
Following up from #325 and in light of recent workarounds downstream in https://github.com/python-poetry/poetry/pull/5654, we would also want #365 to be considered for b1.

**Review by radoering — COMMENTED** [review]
Recently merged PRs which may or may not need an changelog entry: #365, #325, #358

**Pull request merged**
