### PR TITLE
Keep _constraint and _pretty_constraint of Dependency synchronized when calling set_constraint()

### PR DESCRIPTION
**Pull request by radoering**
Resolves: python-poetry/poetry#4589

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Review by neersighted — COMMENTED** [review]
Is there a compelling reason we can't remove the internal property and rely on the getter to call str()? I'm not super familiar with the code here, but this just seems to be much more error-prone than computing the value on demand.

**Comment by radoering** [comment]
The only reason I can imagine (without having examined it) is performance.

**Comment by neersighted** [comment]
Let's go ahead and drop the property then -- I think that implementation will be much more obviously correct and will not allow things to get out of sync in the future.

**Comment by radoering** [comment]
After dropping the property, I had to adapt some tests because the constraint style changed. With the property pretty_constraint was determined before parsing the constraint, now it is determined after parsing the constraint.

**Comment by neersighted** [comment]
> After dropping the property, I had to adapt some tests because the constraint style changed. With the property pretty_constraint was determined before parsing the constraint, now it is determined after parsing the constraint.

Gah, looks like it's a pretty leaky abstraction overall. I'm inclined to just roll back to your first changeset and plan to refactor this later.

**Comment by radoering** [comment]
No problem. In any case, less risky.

**Review by neersighted — APPROVED** [review]

**Pull request merged**
