### PR TITLE
Add monthly downloads badge to README

### PR DESCRIPTION
**Pull request by Aman-Clement**
Added a monthly downloads badge by pip Trends to the README.
View more at - https://piptrends.com/widgets/poetry-core

### CODE REVIEW

**Comment by ixmatus** [comment]
This person tried to open this exact PR against a project I'm the maintainer for as well (https://github.com/ixmatus/inflector/pull/16). This is a promotional campaign and they (or colleagues) appear to be doing it on reddit too, I think this is suspicious activity. They are creating an external dependency on a web property that (as far as I can tell) is not officially blessed by pypi. I recommend rejecting this PR.

Users can get package statistics from `libraries.io` which is linked to directly by pypi itself.

**Comment by edgarrmondragon** [comment]
Yeah I don't see how this is better than shields.io:

PyPI - Downloads

**Comment by ayushjain01** [comment]
Thank you for your feedback and concerns. I'd like to clarify that this is not a promotional campaign. As stated in the PR description, our intention is simply to share a tool we have developed, which we believe could be beneficial to the community.

Our badge system offers highly accurate statistics, which is why we wanted to make it available. If the link to the pip trends page is a concern, we are more than willing to remove it.

We respect your decision if you prefer not to add more badges to your README. Our primary goal is to address any misunderstandings and assure you that this is a genuine effort to contribute to the open-source community by sharing our work on GitHub.

Thank you for considering our contribution.

**Comment by ayushjain01** [comment]
> Yeah I don't see how this is better than shields.io:
> 
> PyPI - Downloads


Here's how our badge is better than the existing badges - 
Sheilds.io - PyPI - Downloads
pepy.tech - [Downloads](https://pepy.tech/project/poetry-core)
pip trends -[poetry-core Downloads Last Month](https://piptrends.com/package/poetry-core)


You can see the difference in the download counts on all these badges. The pip trends badge count is the most accurate count and can be verified using - 
```sql
SELECT COUNT(*) AS num_downloads
FROM `bigquery-public-data.pypi.file_downloads`
WHERE file.project = 'poetry-core'
  -- Only query the last 30 days of history
  AND DATE(timestamp)
    BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
    AND CURRENT_DATE()
```

You can read more and verify using this link - https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/#counting-package-downloads

**Comment by Secrus** [comment]
Yeah, I don't think this is really needed, pass

**Pull request closed without merging**
