### PR TITLE
Allow path dependency that is missing build-system

### PR DESCRIPTION
**Pull request by oysols**
Missing [build-system] table should be allowed.
Poetry handles this fine, except for this check.

> Tools should not require the existence of the [build-system] table.
https://packaging.python.org/en/latest/specifications/pyproject-toml/

---

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by dimbleby** [comment]
per the PEP, the correct check for `supports_pep517` would be

> If the pyproject.toml file is absent, or the build-backend key is missing, the source tree is not using this specification

the section that you quote relates to PEP518's `build-system`, not PEP517's `build-backend`

**Comment by oysols** [comment]
I agree. This implements the simplified solution to this issue. The alternative would be deep validation of the toml file.

**Comment by radoering** [comment]
I still don't understand what kind of problem you're trying to solve. Is it just that the name of the method does not match the current implementation or is there a deeper issue? (Afaik, a path dependency without a build system (and no setup.py/setup.cfg) is not installable from Poetry's point of view and thus is not supported so maybe we should just rename the method to `is_installable_python_project()`?)

Further, the following message is now even more outdated than before:

https://github.com/python-poetry/poetry-core/blob/56c03764e1359615adfcacab12ababd7c57a0e90/src/poetry/core/packages/dependency.py#L407-L411

**Comment by oysols** [comment]
A path dependency without a build system IS installable by Poetry, but this check blocked the installation. I tried to describe the issue with the new test case. As I read the spec (as linked earlier) that pyproject.toml should be valid and installable.

**Comment by dimbleby** [comment]
indeed according to `pip`'s reading, even an empty `pyproject.toml` is enough to define an installable package:
```console
$ pip install .
Processing /home/dch/foo
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=923 sha256=1c1ca2513e561152af25077228c0b0adcc3e7bf389b9423e5db0fa0b185a6ada
  Stored in directory: /tmp/pip-ephem-wheel-cache-jgkqf7p1/wheels/74/36/59/5f272a8602c0655288a982d06e0ec48e94c6c3ccfe9d1f1d69
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```

**Comment by radoering** [comment]
> A path dependency without a build system IS installable by Poetry

Ah, of course it is since `setuptools` supports pyproject.toml. 🤦

Then, this makes sense of course and we should only change the error message I have already mentioned in https://github.com/python-poetry/poetry-core/pull/675#issuecomment-1859192332.

> indeed according to pip's reading, even an empty pyproject.toml is enough to define an installable package:

Weird...

**Review by radoering — APPROVED** [review]

**Pull request merged**
