### PR TITLE
use mypy to lint 'tests' directory

### PR DESCRIPTION
**Pull request by danieleades**
what it says on the tin.

is this something we want or are we getting carried away now?

### CODE REVIEW

**Comment by neersighted** [comment]
I think this is a bit longer off -- long-term it would be good, but for now I think it's tilting and windmills and not that productive. Happy to hear from others, however.

**Comment by danieleades** [comment]
Perhaps a little quixotic

**Comment by neersighted** [comment]
> 
> 
> Perhaps a little quixotic

You know what, we're doing this in `poetry` itself, so I'm personally open to it.

**Comment by danieleades** [comment]
rebased

**Review by neersighted — APPROVED** [review]

**Pull request merged**
