### PR TITLE
Fix wheel data section to use normalised package name, and test

### PR DESCRIPTION
**Pull request by robtaylor**
Resolves: python-poetry/poetry#7117

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Review by radoering — APPROVED** [review]

**Comment by radoering** [comment]
@robtaylor I rebased your branch for merging and missed that you had merged the main branch before, so the author information is now incorrect. Can you please re-commit with your account?

**Review by radoering — CHANGES_REQUESTED** [review]
@robtaylor I rebased your branch for merging and missed that you had merged the main branch before, so the author information is now incorrect. Can you please re-commit with your account?

**Comment by radoering** [comment]
> I rebased your branch for merging and missed that you had merged the main branch before, so the author information is now incorrect.

It seems the author information is still correct. I was just confused by github only displaying my avatar. The reason is probably that you committed with an e-mail address that is not connected to your account. If I squash your PR, another address will be used.

**Comment by robtaylor** [comment]
Ah perfect, I was surprised it didn’t have the right author info.

I’m happy for it to be squashed if necessary.

**Review by radoering — APPROVED** [review]

**Pull request merged**
