### PR TITLE
allow appending deployment key to username (#2062) 

### PR DESCRIPTION
**Pull request by finswimmer**
This PR allows appending deployment keys to usernames as used by gitlab. 

Furthermore a new property `is_unsafe` is introduced for `ParsedUrl`, which can be used for cli command like `poetry add` to easily return whether the git dependency contains a password.

According to [gitlab's docs](https://docs.gitlab.com/ee/user/project/deploy_tokens/) a `+` is allowed in usernames. This is fixed as well.

Fixes: https://github.com/python-poetry/poetry/issues/2062

(This was initially submitted to the poetry repository: https://github.com/python-poetry/poetry/pull/2169)

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://python-poetry.org/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by setu4993** [comment]
Thanks for this, @finswimmer!

I noticed one thing that it doesn't explicitly tests for / address is using Personal Access Tokens (https://github.com/python-poetry/poetry/issues/2348). It might work, but would be nice to add a test for it to avoid issues.

[GitHub docs](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) about it.

Also, is there anything that I can contribute on this that could help speed things up? Thanks!

**Comment by setu4993** [comment]
Bumping this up again, @finswimmer to ask if there's any specific areas I can help building / supporting that can help speed this up?

Thanks for all your work!

**Comment by setu4993** [comment]
@finswimmer : I took a stab at the remainder items here that'd help in resolving https://github.com/python-poetry/poetry/issues/2062 and https://github.com/python-poetry/poetry/issues/2348, and based it off of the branch for this PR. https://github.com/finswimmer/core/pull/1

**Comment by jedie** [comment]
Any news here?!?

**Pull request closed without merging**
